name: CI_db_server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: read

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Configuracion de JDK 25 (Temurin)
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          check-latest: true
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      
      - name: Compilacion y Tests
        env:
          DB_HANDSHAKE_SECRET: ${{ secrets.DB_HANDSHAKE_SECRET }}
        run: |
          chmod +x ./mvnw
          ./mvnw clean package
